# Generated by Django 5.1.5 on 2025-01-22 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MiniatureGallery.category')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=128)),
                ('utype', models.CharField(choices=[('Horde', 'Horde'), ('Infantry', 'Infantry'), ('Character', 'Character'), ('Epic Character', 'Epic Character'), ('Vehicle', 'Vehicle'), ('Monster', 'Monster'), ('Titan', 'Titan'), ('Display', 'Display')], default='Infantry', max_length=16)),
                ('points', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MiniatureGallery.category')),
            ],
        ),
    ]
