# Generated by Django 5.1.5 on 2025-01-23 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiniatureGallery', '0002_rename_name_text_unit_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Kit Name')),
                ('count', models.IntegerField(default=1, verbose_name='Kit Number')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Storage Tag')),
                ('location', models.CharField(max_length=128, verbose_name='Stored Location')),
                ('last_moved', models.DateField(default=None, null=True, verbose_name='Last Moved')),
                ('current_cap', models.IntegerField(choices=[(0, 'Empty'), (1, 'Partialy Full'), (2, 'Half Full'), (3, 'Mostly Full'), (4, 'Full')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Tag')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MiniatureGallery.category', verbose_name='Parent Category'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MiniatureGallery.category', verbose_name='Categorization'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Unit Name'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Points Per Model'),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='Miniature Count')),
                ('note', models.CharField(default='', max_length=512, verbose_name='Extra Note(s)')),
                ('edit_date', models.DateField(default=None, null=True, verbose_name='Last Edited')),
                ('stage', models.CharField(choices=[('Unopened', 'Unopened'), ('Building', 'Building'), ('Magnetizing', 'Magnetizing'), ('Priming', 'Priming'), ('Painting', 'Painting'), ('Basing', 'Basing'), ('Varnishing', 'Varnishing'), ('Completed', 'Completed'), ('Repairing', 'Repairing')], default='Unopened', max_length=16)),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MiniatureGallery.unit', verbose_name='Representing Unit')),
                ('kit_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MiniatureGallery.kit', verbose_name='Source Kit')),
                ('storage_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MiniatureGallery.storage', verbose_name='Current Storage')),
            ],
        ),
        migrations.CreateModel(
            name='BatchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.ImageField(default='fallback.png', upload_to='uploads/', verbose_name='Image')),
                ('upload_date', models.DateField(default=None, null=True, verbose_name='Upload Date')),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiniatureGallery.batch', verbose_name='Batch Image')),
            ],
        ),
        migrations.CreateModel(
            name='TagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiniatureGallery.batch', verbose_name='Batch')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MiniatureGallery.tag', verbose_name='Tag')),
            ],
        ),
    ]
