# Generated by Django 5.1.5 on 2025-01-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiniatureGallery', '0003_kit_storage_tag_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='note',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Extra Note(s)'),
        ),
    ]
