# Generated by Django 5.1.5 on 2025-01-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiniatureGallery', '0004_alter_batch_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='current_cap',
            field=models.IntegerField(choices=[(0, 'Empty'), (1, 'Partially-Full'), (2, 'Half-Full'), (3, 'Mostly-Full'), (4, 'Full')], default=0),
        ),
        migrations.AlterField(
            model_name='storage',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Storage Tag'),
        ),
    ]
