# Generated by Django 5.1.5 on 2025-01-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiniatureGallery', '0005_alter_category_name_alter_storage_current_cap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchimage',
            name='img_path',
            field=models.ImageField(upload_to='uploads/', verbose_name='Image'),
        ),
    ]
