# Generated by Django 5.1.5 on 2025-01-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiniatureGallery', '0006_alter_batchimage_img_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='stage',
            field=models.IntegerField(choices=[(0, 'Unopened'), (1, 'Building'), (2, 'Magnetizing'), (3, 'Priming'), (4, 'Painting'), (5, 'Basing'), (6, 'Varnishing'), (7, 'Completed'), (8, 'Repairing')], default=0),
        ),
    ]
