# Generated by Django 5.1.5 on 2025-01-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiniatureGallery', '0007_alter_batch_stage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name': 'Batch', 'verbose_name_plural': 'Batches'},
        ),
        migrations.AlterModelOptions(
            name='batchimage',
            options={'verbose_name': 'Batch Image', 'verbose_name_plural': 'Batch Images'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='kit',
            options={'verbose_name': 'Kit', 'verbose_name_plural': 'Kits'},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'verbose_name': 'Storage', 'verbose_name_plural': 'Storage Containers'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='tagassignment',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tag Assignments'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
        migrations.AddField(
            model_name='kit',
            name='acqu_date',
            field=models.DateField(default=None, null=True, verbose_name='Acquisition Date'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='stage',
            field=models.IntegerField(choices=[(0, 'Unopened'), (1, 'Building'), (2, 'Magnetizing'), (3, 'Priming'), (4, 'Painting'), (5, 'Basing'), (6, 'Varnishing'), (7, 'Repairing'), (8, 'Completed')], default=0),
        ),
        migrations.AlterField(
            model_name='unit',
            name='utype',
            field=models.CharField(choices=[('Horde', 'Horde'), ('Infantry', 'Infantry'), ('Character', 'Character'), ('Epic Character', 'Epic Character'), ('Vehicle', 'Vehicle'), ('Monster', 'Monster'), ('Titan', 'Titan'), ('Display', 'Display')], default='Infantry', max_length=16, verbose_name='Unit Type'),
        ),
    ]
