# Generated by Django 5.1.5 on 2025-02-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiniatureGallery', '0008_alter_batch_options_alter_batchimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchimage',
            name='img_path',
            field=models.ImageField(max_length=255, upload_to='uploads/', verbose_name='Image'),
        ),
    ]
